config/routes.rb
WhatGives::Application.routes.draw do

  devise_for :users
  
  root 'home#index'

  get '/home/about.html', to: "home#about", as: :about

  resources :users 
  resources :contacts do
    resources :interactions
    resources :donations
  end 
end 

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :first_name, :last_name, presence: true
	belongs_to :user
	has_many :interactions
	has_many :donations
	acts_as_taggable # Alias for acts_as_taggable_on :tags
  #acts_as_taggable_on :tags

	def self.search_for(query)
 		Contact.where("first_name LIKE :query OR last_name LIKE :query OR company LIKE :query", query: "%#{query}%")
	end

	def total_donations
		donations.sum(:amount)
	end	

	def high_roller?
		total_donations > 500 
	end	
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :contact

  def self.total_donations
    sum(:amount)
  end

end 

app/models/interaction.rb
class Interaction < ActiveRecord::Base
  belongs_to :contact
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :contacts
has_many :interactions
has_many :donations, through: :contacts

	def interactions_for(contact)	
		interactions.where(contact: contact)
	end     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!, :except=> :about
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def index
  	@contacts = current_user.contacts.search_for(params[:query])
  	#if params[:tag]
   		#@contacts = current_user.contacts.tagged_with(params[:tag])
  	#else
    #	@contacts = current_user.contacts.search_for(params[:query])
    #end	
  	#@contacts = Contact.contacts.search_for(params[:query])
  	#@contacts = Contact.all
  	#@contacts = Contact.where("first_name OR last_name LIKE?", "%#{params[:query]}%")
  end
  
  #def search
  	#@contacts = Contact.where("first_name OR last_name LIKE?", "%#{params[:query]}%")
  #end
  	
  def show
  	@contact = current_user.contacts.find(params[:id])
  	@interaction = Interaction.new
  	@donation = Donation.new
  	#@high_roller = Donation.high_roller
  end
  
  def new
  	@contact = Contact.new
  end
  
  def create
    @contact = current_user.contacts.new(contact_params)
    if @contact.save
      redirect_to "/contacts/#{@contact.id}"
    else
      flash[:error] = "Sorry! Error in creating your contact."
      redirect_to new_contact_path
    end
  end
  
  def edit
  	@contact = Contact.find(params[:id])
  end
  
  def update
    @contact = Contact.find(params[:id])
    if @contact.update_attributes(contact_params)
      redirect_to contact_path(params[:id])
    else
  		flash[:error] = "Sorry! Error in creating your contact."
      render :edit
    end
  end
  
  def destroy
  	@contact = Contact.find(params[:id])
  	@contact.destroy
  	redirect_to "/contacts"
  end
  
  private
  def contact_params
  	params.require(:contact).permit(:first_name, :last_name, :company, :email, :address, :linked_in, :bio, :phone_number, :tag_list)
  end
end  	

app/controllers/donations_controller.rb
class DonationsController < ApplicationController

 def create
		@contact = Contact.find(params[:contact_id])
		@donation = Donation.create(donation_params)
		@contact.donations << @donation 
		redirect_to contact_path @contact, notice: 'New donation!'
	end	

  def destroy
    donation = Donation.find(params[:id])
    donation.destroy
    contact_id = params[:contact_id].to_i
    redirect_to "/contacts/#{contact_id}"
  end	

private
	def donation_params
		params.require(:donation).permit(:date, :amount, :contact_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

before_filter :authenticate_user!, :except=> :about

		#if user_signed_in?
		#redirect_to "/users"

	def index
    @tags = Contact.tag_counts_on(:tags)
	end	

	def about
	end

end	

app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController
  
 def create
		@contact = Contact.find(params[:contact_id])
		@interaction = Interaction.create(interaction_params)
		@contact.interactions << @interaction 
		redirect_to contact_path @contact, notice: 'New interaction!'
	end	

  def destroy
    interaction = Interaction.find(params[:id])
    interaction.destroy
    contact_id = params[:contact_id].to_i
    redirect_to "/contacts/#{contact_id}"
  end	

private
	def interaction_params
		params.require(:interaction).permit(:interacted_at, :note, :contact_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		
	end	

end	

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interaction_helper.rb
module InteractionHelper
end

app/views/contacts/edit.html.erb
<h1>Update Who Gives</h1>

<div class="errors">
  <% if flash[:error] %>
    <p class="alert alert-danger"><%= flash[:error] %></p>
  <% end %>
  <% if flash[:notice] %>
    <p class="alert alert-warning"><%= flash[:notice] %></p>
  <% end %>
</div>

<%= form_for @contact, role: "form" do |form| %>
<section class="contact_form" >
	<div class="form-group">
		<%= form.label :first_name %>
		<%= form.text_field :first_name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= form.label :last_name %>
		<%= form.text_field :last_name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= form.label :company %>
		<%= form.text_field :company, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= form.label :email %>
		<%= form.email_field :email, class: "form-control" %>
	</div>	
	<div class="form-group">
		<%= form.label :phone_number %>
		<%= form.telephone_field :phone_number, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= form.label :address %>
		<%= form.text_area :address, class: "form-control" %>
	</div>	
	<div class="form-group">
		<%= form.label :linked_in %>
		<%= form.url_field :linked_in, class: "form-control" %>
	</div>	
	<div class="form-group">
		<%= form.label :bio %>
		<%= form.text_area :bio, class: "form-control" %>
	</div>	
	<div class="form-group">
		<%= form.label :tag_list %>
		<%= form.text_area :tag_list, class: "form-control" %>
	</div>	
	<br/>
	<%= form.submit class: "btn btn-info btn-xs" %>
<% end %>
<%= link_to 'Back', contacts_path, class: "btn btn-info btn-xs" %>
</section>	

app/views/contacts/index.html.erb
<div class="page-header">
  <h1>Who Gives?<small> View and manage your contacts</small></h1>
</div>

<%= form_tag contacts_path, method: :get do %>
<%= text_field_tag :query, params[:query],  placeholder: "Who Gives?" %>
<%= submit_tag "Search Contacts", class: "btn btn-info btn-sm" %>
<% end %>
<br/>
<%= link_to "Add a new contact", new_contact_path, class: "btn btn-info" %>
  
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th>Company</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Total Donations</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= link_to contact.first_name, contact_path(contact) %></td>
        <td><%= link_to contact.last_name, contact_path(contact) %></td>
        <td><%= contact.company %></td>
        <td><%= contact.email %></td>
        <td><%= number_to_phone(contact.phone_number) %></td>
        <td><%= number_to_currency(contact.total_donations) %></td>  
        <td><%= link_to "Update", edit_contact_path(contact) %>
        <%= link_to "Delete", contact_path(contact), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/contacts/new.html.erb
<h1>Add a new contact </h1>

<%= form_for @contact, role: "form" do |form| %>
<section class="contact_form" >	
	<div class="form-group">
		<%= form.label :first_name %>
		<%= form.text_field :first_name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= form.label :last_name %>
		<%= form.text_field :last_name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= form.label :company %>
		<%= form.text_field :company, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= form.label :email %>
		<%= form.email_field :email, class: "form-control" %>
	</div>	
	<div class="form-group">
		<%= form.label :phone_number %>
		<%= form.telephone_field :phone_number, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= form.label :address %>
		<%= form.text_area :address, class: "form-control" %>
	</div>	
	<div class="form-group">
		<%= form.label :linked_in %>
		<%= form.url_field :linked_in, class: "form-control" %>
	</div>	
	<div class="form-group">
		<%= form.label :bio %>
		<%= form.text_area :bio, class: "form-control" %>
	</div>
	<br/>
	<%= form.submit class: "btn btn-info btn-xs"  %>
<% end %>

<%= link_to 'Back', contacts_path, class: "btn btn-info btn-xs" %>
</section>	

app/views/contacts/show.html.erb
<div class="page-header">
  <h1><%= @contact.first_name %> <%= @contact.last_name %><small> gives a...</small></h1>
</div>

<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12">
    <% @contact.tag_list.each do |tag| %>
      <div class="label label-default"><%= tag %></div>
    <% end %>
  </div>
</div>

<br>

<div class="row">
	<div class="col-md-6">
	<b>Company:</b><%= @contact.company %>
	<br/>
	<b>Email:</b><%= @contact.email %>
	<br/>
	<b>Phone:</b><%= number_to_phone(@contact.phone_number) %>
	<br/>
	<b>Address:</b><%= @contact.address %>
	<br/>
	<b>LinkedIn</b><%= @contact.linked_in %>
	<br/>
	<b>Bio:</b><%= @contact.bio %>
	<br/>
	<p><%= link_to 'Edit', edit_contact_path, class: "btn btn-info btn-xs"%>
	<%= link_to 'Back', contacts_path, class: "btn btn-info btn-xs" %>
	</div>

	<div class="col-md-6">
	<h4>How much did they give?</h4>
	<b><%= number_to_currency(@contact.total_donations) %></b>
	<br/>
	<% if @contact.high_roller? %>
		<p><b><i>Gives a damn!</i></b></p>
	<% end %>

	<h5>When and in what amount?</h5>
	<%= form_for [@contact, @donation] do |f|  %>
		<%= f.label :date %>
		<%= f.date_select :date %>
	<br/>
		<%= f.label :amount %>
		<%= f.text_field :amount %>
	<br/>
		<%= f.submit class: "btn btn-info btn-xs" %>
	<% end %> 

	<% @contact.donations.each do |donation| %>
		<p><%= donation.date %></p>
		<p><b><%= number_to_currency(donation.amount) %></b></p>
		<%= link_to 'Delete', contact_donation_path(donation.contact_id, donation.id), confirm: 'Are you sure?', method: :delete, class: "btn btn-info btn-xs"%>
	<% end %>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
	<h4>Interactions</h4>
	<%= form_for [@contact, @interaction] do |f|  %>
		<%= f.label :interacted_at %>
		<%= f.datetime_select :interacted_at %>
	<br/>
		<%= f.label :note %>
		<%= f.text_area :note %>
	<br/>
		<%= f.submit class: "btn btn-info btn-xs" %>
	<% end %> 

	<% @contact.interactions.each do |interaction| %>
		<p><%= interaction.interacted_at %></p>
		<p><%= interaction.note %> </p>
		<%= link_to 'Delete', contact_interaction_path(interaction.contact_id, interaction.id), confirm: 'Are you sure?', method: :delete, class: "btn btn-info btn-xs"%>
	<% end %>
</div>

	

	

	 

	

app/views/home/about.html.erb
<body class="homebg">
<div class="jumbotron">
  <h1>About What Gives?</h1>
  <h2>Manage your donors better</h2>
  <p>Let's face it. Most donor management systems suck. What Gives? enables you to easily track contacts, donors and prospects with a modern, clean interface. </p>
  <p><%= link_to "Sign Up", new_registration_path(User), class: "btn btn-primary btn-lg" %>
  <%= link_to "Sign In", new_session_path(User), class: "btn btn-primary btn-lg"%></p>
</div>
<P> What Gives? was made by <%= link_to "Eleanor Callott Whitney", "http://eleanorcwhitney.com"%> for <%= link_to "General Assembly's", "https://generalassemb.ly/"%> Back End Web Development class in February 2014. Updates? Suggestions? Follow along on <%= link_to "Github", "https://github.com/EleanorCallottWhitney/what_gives"%>. What Gives? was built on Ruby on Rails using <%= link_to "Devise", "https://github.com/plataformatec/devise" %> for authentication and <%= link_to "Bootstrap", "http://getbootstrap.com/" %> for styling. Drop a line at <%= mail_to "eleanor.whitney@gmail.com" %></p>
<p>Many, many thanks to Eric Collins, Jamal Powell, Zachary Reitano, Scott Carleton, Bill Mantegna, Vish Reddy, Kirsten Nordine, Nick Patch, Michael Zole, Erin M. Kidwell, and Ari Russo for all of your help and encouragement!</p> 
</div>

app/views/home/index.html.erb
<body class="homebg">

<div class="page-header">
  <h1>What Gives?<small> Who Gives?</small></h1>
</div>

<br/>

<div class="row">
  <div class="col-md-4">
  	<div class="text">
  		<p><b>View and manage who gives</b></p>
  	</div>	
  	<%= link_to "Contacts", contacts_path, class: "btn btn-primary"%>
  </div>
  <div class="col-md-4">
  	<div class="text">
  		<p><b>How much have they given?</b></p>
  	</div>
  	<button class="btn btn-default"><%= number_to_currency(current_user.donations.total_donations) %></button>
  </div>
  <div class="col-md-4"><p></p></div>
</div>
</body>

app/views/interaction/edit.html.erb
<h1>Edit Interaction</h1>
<p></p>

app/views/interaction/index.html.erb
<h1>Interaction#index</h1>
<p>Find me in app/views/interaction/index.html.erb</p>

app/views/interaction/new.html.erb
<h1>Interaction#new</h1>
<p>Find me in app/views/interaction/new.html.erb</p>

app/views/interaction/show.html.erb
<h1>Interaction#show</h1>
<p>Find me in app/views/interaction/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhatGives</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

 <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
  <a class="navbar-brand" href="/">What Gives?</a>
  <ul class="nav navbar-nav">
      <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Contacts", contacts_path %></li>
        <li><%= link_to "New contact", new_contact_path %></li>
      <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>  
      <li><p class="navbar-text">What gives <%= current_user.email %>? </p></li>
      <% else %>
      <%- if controller_name != 'sessions' %>
      <li><%= link_to "Sign in", new_session_path(User) %></li>
    <% end -%>
      <li>  <%= link_to "Sign up", new_registration_path(User) %></li>
    <% end %>
   </ul>     
  </div>
</nav> 

	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  
<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>users will have lots of contacts giving them money! </h1>